main_site/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('user/',include('user.urls',namespace='user')),
    path('services/',views.services,name='services')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views
# SET THE NAMESPACE!
app_name = 'user'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('special/',views.special,name='special'),
    path('logout/',views.user_logout,name='logout'),
    path('panel/',include('userpanel.urls',namespace='userpanel')),
]

templates/base1.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>NervAI</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- jquery -->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'index' %}"> <img src="{% static 'img/log.png' %}" alt="logo" style="height: 70px;width: 260px;"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'services' %}">Services</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#footer-block">Contact</a>
                                </li>
                
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'user:userpanel:panel' %}">Hello, {{user.username}}</a>  
                                </li>
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>  
                                </li>
                                {% else %}
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'user:user_login' %}">Sign In</a>
                                </li>
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
                                </li>
                                {% endif %}

                            </ul>
                        </div>
                        <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                        
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->


    {% block body_block %}
    {% endblock %}

    
    <!--::footer_part start::-->
    <footer id="footer-block" class="footer_part">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-lg-4">
                    <div class="single_footer_part">
                        <a href="{% url 'index' %}" class="footer_logo_iner"> <img src="{% static 'img/logo foot.png' %}" alt="#" style="height: 50px;width: 220px;"> </a>
                        <h4>About Us</h4>
                        <p>We are the developers who can play football!!</p>
                    </div>
                </div>
                <div class="col-sm-4 col-lg-4">
                    <div class="single_footer_part">
                        <h4>Contact Info</h4>
                        <p>Address : You can find us <br>
                            in the virtual world!!
                        </p>
                        <p>Phone : +8880 44338899</p>
                        <p>Email : info@nerve.ai</p>
                    </div>
                </div>
        
                <div class="col-sm-4 col-lg-4">
                    <div class="single_footer_part">
                        <h4>Developed By:</h4>
                        <p><em>B K J S</em></p>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-8">
                    <div class="copyright_text">
                        <P>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved.</P>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer_icon social_icon">
                        <ul class="list-unstyled">
                            <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

    <!-- jquery plugins here-->
    <!-- popper  js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstr static ap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing  static js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper  static js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper  static js -->
    <script src="{% static 'js/masonry.pkgd.js' %}"></script>
    <!-- particl static es js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick j static s -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom  static js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/createBot.html
{% extends "panelbase.html" %}
{% block body_block %}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">

        <h2>Create a new Bot</h2>
    </div>

    <div class="col-lg-5">
        <form method="post" enctype="multipart/form-data" action="{% url 'user:userpanel:createBot' %}">
            {% csrf_token %}
            <div class="panel border border-primary rounded p-4">
                <div class="panel-heading">
                    <h3 class="panel-title">Bot Details</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="c_name">Bot Name</label>
                        <input type="text" name="bot_name" class="form-control w-50" placeholder="Enter Bot Name"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="c_desc">Bot Description</label>
                        <textarea type="text" name="bot_desc" class="form-control"
                            placeholder="What is your bot purpose?"></textarea>
                    </div>
                    <div class="form-group">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="lang">Language</label>
                            </div>
                            <select class="custom-select" id="lang" name="lang_code" required>
                                <option value="en-us" selected>English-US</option>
                                <option value="en-uk">English-UK</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>


            <input class="btn btn-primary btn-lg btn-block mt-4" type="submit" value="Create">
        </form>
    </div>

</main>


{% endblock %}

templates/feature.html
{% extends "base1.html" %}
{% block body_block %}
{% load static %}

    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>featured</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!-- feature_part start-->
    <section class="feature_part padding_top">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-6 ">
                    <div class="row align-items-center">
                        <div class="col-lg-6 col-sm-6">
                            <div class="single_feature">
                                <div class="single_feature_part">
                                    <img src="{% static 'img/icon/feature_icon_1.png' %}" alt="">
                                    <h4>A Volunteer</h4>
                                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-6">
                            <div class="single_feature">
                                <div class="single_feature_part">
                                    <img src="{% static 'img/icon/feature_icon_2.png' %}" alt="">
                                    <h4>A Volunteer</h4>
                                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
                                </div>
                            </div>
                            <div class="single_feature">
                                <div class="single_feature_part single_feature_part_2">
                                    <img src="{% static 'img/icon/feature_icon_3.png' %}" alt="">
                                    <h4>A Volunteer</h4>
                                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="feature_part_text">
                        <h2>featured</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse
                            ultrices gravida Risus com odo viverra maecenas accumsan lacus vel facilisis
                            accumsan.</p>
                        <div class="row">
                            <div class="col-sm-6 col-md-4 col-lg-5">
                                <div class="feature_part_text_iner">
                                    <h4>50k</h4>
                                    <p>Total Volunteer</p>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-5">
                                <div class="feature_part_text_iner">
                                    <h4>100k</h4>
                                    <p>Successed Mission</p>
                                </div>
                            </div>
                        </div>
                        <a href="#" class="btn_4">learn more <img src="{% static 'img/icon/right-arrow.svg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
        
        <img src="{% static 'img/animate_icon/Shape-1.png' %}" alt="" class="feature_icon_1">
        <img src="{% static 'img/animate_icon/Shape-14.png' %}" alt="" class="feature_icon_2">
        <img src="{% static 'img/animate_icon/Shape.png' %}" alt="" class="feature_icon_3">
        <img src="{% static 'img/animate_icon/shape-3.png' %}" alt="" class="feature_icon_4">
    </section>
    <!-- upcoming_event part start-->

    <!-- about_us part start-->
    <section class="about_us section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-5">
                    <div class="about_us_text">
                        <h2>Right people at the
                            Right time.</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna
                            aliqua. Ut enim ad minim</p>
                        <a href="#" class="btn_1">get started</a>
                        {% if user.is_anonymous%}
                            <a href="{% url 'user:register' %}" class="btn_2 banner_btn_2">Sign up for free </a>
                        {% endif %}
                        </div>
                </div>
                <div class="col-md-6 col-lg-6">
                    <div class="learning_img">
                        <img src="{% static 'img/about_img.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'img/left_sharp.png' %}" alt="" class="left_shape_1">
        <img src="{% static 'img/about_shape.png' %}" alt="" class="about_shape_1">
        <img src="{% static 'img/animate_icon/Shape-16.png' %}" alt="" class="feature_icon_1">
        <img src="{% static 'img/animate_icon/Shape-1.png' %}" alt="" class="feature_icon_4">
    </section>
    <!-- about_us part end-->

    <!-- cta part start-->
    <section class="cta_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-6">
                    <div class="cta_text text-center">
                        <h2>Very useful Friendly</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna
                            aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo</p>
                        <a href="#" class="btn_2 banner_btn_1">Get Started </a>
                        {% if user.is_anonymous%}
                            <a href="{% url 'user:register' %}" class="btn_2 banner_btn_2">Sign up for free </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- cta part end-->

{% endblock %}

templates/index.html
{% extends "base1.html" %}
{% block body_block %}
{% load static %}
    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row mt-ng align-items-center">
                <div class="col-lg-7">
                    <div class="banner_text">
                        <div class="banner_text_iner">
                            <h1>Drive More Customers
                                Through Digital</h1>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                sed do eiusmod tempor incididunt ut labore et dolore magna
                                aliqua. Ut enim ad minim veniam.</p>
                            <a href="#" class="btn_2 banner_btn_1">Get Started </a>
                            {% if user.is_anonymous%}
                            <a href="{% url 'user:register' %}" class="btn_2 banner_btn_2">Sign up for free </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="banner_img d-none d-lg-block">
                        <img src="{% static 'img/banner_img.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->

  
    <!-- upcoming_event part start-->

    <!-- about_us part start-->
    <section class="about_us section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-5">
                    <div class="about_us_text">
                        <h2>Right people at the
                            Right time.</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna
                            aliqua. Ut enim ad minim</p>
                        <a href="#" class="btn_1">get started</a>
                        {% if user.is_anonymous%}
                            <a href="{% url 'user:register' %}" class="btn_2 banner_btn_2">Sign up for free </a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6 col-lg-6">
                    <div class="learning_img">
                        <img src="{% static 'img/about_img.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'img/left_sharp.png' %}" alt="" class="left_shape_1">
        <img src="{% static 'img/about_shape.png' %}" alt="" class="about_shape_1">
        <img src="{% static 'img/animate_icon/Shape-16.png' %}" alt="" class="feature_icon_1">
        <img src="{% static 'img/animate_icon/Shape-1.png' %}" alt="" class="feature_icon_4">
    </section>
    <!-- about_us part end-->

    <!-- use sasu part end-->
    <section class="use_sasu">
        <div class="container pb-5">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section_tittle text-center">
                        <h2>Who can use CaaS?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do
                            eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            Quis ipsum suspendisse ultrices </p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature">
                        <div class="single_feature_part">
                            <img src="{% static 'img/icon/feature_icon_1.png' %}" alt="">
                            <h4>Businesses</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature">
                        <div class="single_feature_part">
                            <img src="{% static 'img/icon/feature_icon_2.png' %}" alt="">
                            <h4>Companies</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature">
                        <div class="single_feature_part">
                            <img src="{% static 'img/icon/feature_icon_3.png' %}" alt="">
                            <h4>Universities</h4>
                            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'img/animate_icon/Shape-10.png' %}" alt="" class="feature_icon_2">
        <img src="{% static 'img/animate_icon/Shape.png' %}" alt="" class="feature_icon_3">
        <img src="{% static 'img/animate_icon/shape-13.png' %}" alt="" class="feature_icon_4">
    </section>
    <!-- use sasu part end-->

    <!-- cta part start-->
    <section class="cta_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-6">
                    <div class="cta_text text-center">
                        <h2>Very useful &amp; Friendly</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna
                            aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo</p>
                        <a href="#" class="btn_2 banner_btn_1">Get Started </a>
                        {% if user.is_anonymous%}
                            <a href="{% url 'user:register' %}" class="btn_2 banner_btn_2">Sign up for free </a>
                        {% endif %}
                        </div>
                </div>
            </div>
        </div>
    </section>
    <!-- cta part end-->

{% endblock %}

templates/login.html
{% extends "base1.html" %}
{% block body_block %}
{% load static %}

<section class="margin_top">
  <div class="container padding_top">
      <div class="row">
          <div class="col-lg-5">
              <div class="banner_text">
                <h1>Sign In</h1>

                <form method="post" action="{% url 'user:user_login' %}">
                    {% csrf_token %}
                    {# A more "HTML" way of creating the login form#}
                    <div class="form-group">
                      <label for="username">Username</label>
                      <input type="text" name="username" class="form-control" placeholder="Enter username">
                      <small id="emailHelp" class="form-text text-muted">We'll never share your username with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                      <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>

              </div>
          </div>
      </div>
    </div>
</section>

{% endblock %}

templates/panelbase.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>NervAI</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="icon" href="{% static 'img/favicon.png' %}">



  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{% static 'userpanel/css/dashboard.css' %}" rel="stylesheet">
</head>

<body>
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">{{ userinfo.c_name }}</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'user:logout' %}">Sign out</a>
      </li>
    </ul>
  </nav>


  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column" id="tab-links">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:userpanel:panel' %}" id="dashboard">
                <span data-feather="home"></span>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:userpanel:createBot' %}" id="createBot">
                <span data-feather="file"></span>
                Create Bot
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="shopping-cart"></span>
                Add Services
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:userpanel:deploy' %}" id="deploy">
                <span data-feather="users"></span>
                Deploy Bot
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="bar-chart-2"></span>
                Reports
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="layers"></span>
                Integrations
              </a>
            </li>
          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
              <span data-feather="plus-circle"></span>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Current month
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Last quarter
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Social engagement
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Year-end sale
              </a>
            </li>
          </ul>
        </div>
      </nav>



      {% block body_block %}
      {% endblock %}


    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script>window.jQuery || document.write("<script src=\"{% static 'js/jquery-3.3.1.slim.min.js' %}\"><\/script>")</script>
  <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'dashboard/js/popper.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script>
      feather.replace()
      $(document).ready(function(){
        let path = window.location.pathname;
        if( path.includes('create')){
          $('#createBot').addClass('active');
        }
        else if( path.includes('deploy')){
          $('#deploy').addClass('active');
        }
        else {
          $('#dashboard').addClass('active');
        }
      });
    </script>
  <script src="{% static 'userpanel/js/dashboard.js' %}"></script>
</body>

</html>